### ISSUE TITLE
关于交流群有个疑问

### ISSUE THREAD

**Issue by df13954** [dqzg12300/FartExt#6]
大佬有没有QQ群或者wx群呢，群可以发布一些公告什么的，然后我们也可以参与测试，或者反馈问题。
如果没有可以直接关掉issue

**Comment by dqzg12300** [comment]
暂时没做啥功能了，今年下半年可能会出个新版本。到时候再弄个专门的群，你可以先到我的fridaUiTools那个群，我明天会更新下群二维码

**Comment by df13954** [comment]
> 暂时没做啥功能了，今年下半年可能会出个新版本。到时候再弄个专门的群，你可以先到我的fridaUiTools那个群，我明天会更新下群二维码

OK，看到了，等更新

**Comment by dqzg12300** [comment]
fridauitools的那个群扫码加入的人数已经满了，我重新开了个rom的群二维码在mikrom的项目中。

**Comment by df13954** [comment]
> fridauitools的那个群扫码加入的人数已经满了，我重新开了个rom的群二维码在mikrom的项目中。

已经入群啦，感谢
